export { ReactComponent as LogoIcon } from './logo.svg'
export { ReactComponent as SunIcon } from './sun.svg'
export { ReactComponent as MoonIcon } from './moon.svg'
export { ReactComponent as MonitorIcon } from './monitor.svg'
export { ReactComponent as ErrorOutlineRoundedIcon } from './error-outline-rounded.svg'
